server:
  port: 8099
spring:
  application:
    name: webconfig
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-samples/config-repo
#      label: master

